feat(JOML): migrate BlockItemSystem and Physics#scanArea
MovingBlocks/Terasology pull request #4193
Opened 2020-10-11 16:44 UTC by pollend

here is some partial work on migrating aabb for physics along with some effort to migrate BlockItemSystem.

2020-10-12 10:39 UTC, DarkWeird requested changes

2020-10-12 10:39 UTC, DarkWeird commented on engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
> +            blockBounds.minX += ADDITIONAL_ALLOWED_PENETRATION;
Seems there must be `-=`

2020-10-12 10:39 UTC, DarkWeird commented on engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
> +    public List<EntityRef> scanArea(AABBf area, Iterable<CollisionGroup> collisionFilter) {
Duplication with old method.

2020-10-22 14:27 UTC, jdrueckert reviewed
@pollend DarkWeird's review comments still seem to apply here.

2020-10-22 14:31 UTC, pollend commented
I need to work on that.

2020-10-31 06:53 UTC, DarkWeird approved these changes

2020-10-31 10:30 UTC, merged