remove afk screen
MovingBlocks/Terasology pull request #4248
Opened 2020-11-14 17:55 UTC by pollend

removed the afk screen and moved the console messages to logging instead. having an popup show up every minute or so is kind of obnoxious. probably just enough to mark the player as afk rather then also notify them that they are afk. I don't think there is really a need to convey this to player in the first place. in single player this popup shows up constantly so that needs to be addressed. 

ref: https://github.com/MovingBlocks/Terasology/pull/3571

2020-11-14 20:06 UTC, skaldarnar requested changes

2020-11-14 20:06 UTC, skaldarnar commented on engine/src/main/java/org/terasology/logic/afk/AfkClientSystem.java
> +            logger.info("[AFK] You are AFK now!");
I think some form of confirmation would be nice... Console is the text box in the bottom left, right? I think we could also print to the dev console by returning a String from this command method.

2020-11-14 20:06 UTC, skaldarnar commented on engine/src/main/java/org/terasology/logic/afk/AfkClientSystem.java
> +            logger.info("[AFK] You are no longer AFK!");
Same here, application logs are not visible to the player.

2020-11-14 20:40 UTC, skaldarnar approved these changes

2020-11-14 22:00 UTC, jdrueckert commented
Closes #4243

2020-11-16 05:09 UTC, pollend commented
is there any other changes we want to make @skaldarnar.

2020-11-16 18:13 UTC, skaldarnar approved these changes

2020-11-16 21:24 UTC, merged