feat(JOML): migrate `character` package events and systems
MovingBlocks/Terasology pull request #4279
Opened 2020-11-25 23:23 UTC by jdrueckert

2020-11-25 23:26 UTC, jdrueckert commented
Should be merged together with the following PRs otherwise omega won't compile anymore:
https://github.com/Terasology/BiomesAPI/pull/7
https://github.com/Terasology/Health/pull/54
https://github.com/Terasology/FlowingLiquids/pull/18
https://github.com/Terasology/Rails/pull/62
https://github.com/Terasology/AdventureAssets/pull/32
https://github.com/Terasology/CombatSystem/pull/59
https://github.com/Terasology/FunnyBlocks/pull/19
https://github.com/Terasology/GooKeeper/pull/32
https://github.com/Terasology/LightAndShadow/pull/174
https://github.com/Terasology/MasterOfOreon/pull/81

2020-11-27 02:09 UTC, pollend approved these changes

2020-11-27 02:18 UTC, pollend requested changes

2020-11-27 02:18 UTC, pollend commented on engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
> +        if (location == null || Float.isNaN(location.getWorldPosition(new Vector3f()).x()) || movementComp == null) {
```suggestion
        if (location == null || !location.getWorldPosition(new Vector3f()).isFinite() || movementComp == null) {
```

2020-11-27 02:18 UTC, pollend commented on engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
> +            result.getRotation().set(JomlUtil.from(new org.terasology.math.geom.Quat4f(TeraMath.DEG_TO_RAD * input.getYaw(), 0, 0)));
```suggestion
            result.getRotation().set(new Quaternionf().rotationYXZ(org.joml.Math.toRadians(input.getYaw()), 0, 0));
```

2020-12-12 15:12 UTC, pollend approved these changes

2020-12-12 19:25 UTC, merged