feat(JOML): migrate world renderer
MovingBlocks/Terasology pull request #4333
Opened 2020-12-26 23:55 UTC by pollend

2020-12-26 23:55 UTC, pollend commented on engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
> +                    }
Hopefully this is migrated correctly.

2020-12-30 22:49 UTC, jdrueckert requested changes

2020-12-30 22:49 UTC, jdrueckert commented on engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
> +            for (Vector3ic toAdd : newRenderableRegion) {
```suggestion
            for (Vector3ic chunkPositionToAdd : newRenderableRegion) {
```

2020-12-30 22:49 UTC, jdrueckert commented on engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
> +                    }
I think you did, yes.

2020-12-30 22:49 UTC, jdrueckert commented on engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
> +            for (Vector3ic toRemove : renderableRegion) {
```suggestion
            for (Vector3ic chunkPositionToRemove : renderableRegion) {
```

2020-12-31 10:55 UTC, jdrueckert approved these changes

2020-12-31 11:21 UTC, merged