feat(JOML): migrate aabb for SkeletonRenderer
MovingBlocks/Terasology pull request #4431
Opened 2021-01-24 19:08 UTC by pollend

2021-01-28 11:14 UTC, DarkWeird requested changes

2021-01-28 11:14 UTC, DarkWeird commented on engine/src/main/java/org/terasology/rendering/gltf/GLTFAnimationFormat.java
> +        return new MeshAnimationData(boneNames, boneParents, frames, TIME_PER_FRAME, new AABBf());
`new AABBf()` creates with (minX, minY, minZ)=(+inf, +inf, +inf) and (maxX, maxY, maxZ)=(-inf, -inf, -inf)

2021-01-28 18:48 UTC, jdrueckert requested changes
This PR seems to break the model rendering.
On current develop I was able to see both deer and gooey citizens in MR, but with this PR checked out the models were invisible.
![image](https://user-images.githubusercontent.com/29981695/106184797-5135ab00-61a2-11eb-8437-6b26f904a286.png)

2021-01-29 07:25 UTC, DarkWeird commented
> This PR seems to break the model rendering.
> On current develop I was able to see both deer and gooey citizens in MR, but with this PR checked out the models were invisible.
> ![image](https://user-images.githubusercontent.com/29981695/106184797-5135ab00-61a2-11eb-8437-6b26f904a286.png)

I think it related to my review. try to find model at infinity :D

2021-01-29 11:31 UTC, skaldarnar approved these changes

2021-01-29 11:31 UTC, skaldarnar commented on engine/src/main/java/org/terasology/rendering/gltf/GLTFAnimationFormat.java
> +        return new MeshAnimationData(boneNames, boneParents, frames, TIME_PER_FRAME, new AABBf(0, 0, 0));
Thanks @DarkWeird , this indeed fixed it.

2021-01-29 11:45 UTC, DarkWeird approved these changes

2021-01-29 12:09 UTC, merged