chore(RegisterMods): make sure thread has a name and is set to daemon
MovingBlocks/Terasology pull request #4547
Opened 2021-02-27 21:27 UTC by keturn

All our threads should have names to help us during debugging.

Most threads should also have daemon=true so they don't prevent the process from closing if they get stuck.

This fixes those things for loadProcesses.RegisterMods.

Like its predecessor #3953, this PR is something of a straw man, as this is a ridiculous amount of boilerplate code to copy every time we want to queue an asynchronous task. Suggestions encouraged.

2021-03-01 09:09 UTC, DarkWeird requested changes

2021-03-01 09:09 UTC, DarkWeird commented on engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterMods.java
> +                applyModulesThread = Executors.newSingleThreadExecutor(
suggestion: Reuse same executor or shutdown executor on done or extends `ThreadManager` to return `Future`

2021-03-01 09:09 UTC, DarkWeird commented on engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterMods.java
> +    private Future<?> applyModulesThread;
suggestion: Rename it.

2022-04-03 22:15 UTC, jdrueckert commented
Closing this as the code changes are no longer relevant with the current transition to Reactor.
The need for naming threads is now tracked in https://github.com/MovingBlocks/Terasology/issues/5005.
The aspect of configuring threads as daemons was added as a TODO for the transition to reactor in https://github.com/MovingBlocks/Terasology/issues/4798

2022-04-03 22:15 UTC, closed without merging