fix(json-config-loading): Fix handling invalid AutoConfigs and config writing
MovingBlocks/Terasology pull request #4660
Opened 2021-05-11 08:11 UTC by DarkWeird

### Contains

* fix invalid json config writing
* add logging when config invalid
* use defaults when config invalid
* Fixes #4642 

### How to test

Chapter 1 (fix writing, require default settings):
1. Open TS
2. Open Settings -> autoconfig
3. change one of setting (set non-default)
4. exit game
5. Open TS
6. Open Settings -> autoconfig
7. change same settings to default
8. exit game
9. check config file - content should be `{}` (all defaults)

Chapter 2 (logging and invalid config):
1. make Config file as invalid - to corrupt json structure
2. Open TS
3. Check Logs - you should see error log entry about config loading error
4. Check how renders invalid config in autoconfig - should be default
5. exit game
6. check config file - content should be `{}` (all defaults) if you don't change settings at (4)

2021-05-11 08:51 UTC, skaldarnar commented on engine/src/main/java/org/terasology/engine/config/flexible/AutoConfigManager.java
> +        } catch (Exception e) {
Hm, I think it is usually a "bad practice" to just capture `Exception`. Do we know what exception can occur here? What else other than `IOException` is thrown here?

2021-05-14 16:48 UTC, jdrueckert requested changes
This worked nicely against that damned SIGSEGV :tada: 
As described, with a broken config it displays the defaults again.

**However**, when I then change some value, it doesn't clean up the broken config from before but simply overwrites parts of it, resulting in again a broken config, e.g.
`{"height":1.75}83,0,255],"playerName":"Player37343"}"height":1.7}`
Before breaking it and starting Terasology again, that's what it looked like:
`{"color":[194,183,0,255],"playerName":"Player37343","height":1.7}`

2021-05-19 14:44 UTC, DarkWeird commented
>I guess keeping the broken one is okay as long as settings are not changed.
If they are changed I'd say we should clean the broken config up before.

It isn't easy. fast way - easy. right way - not so easy.

For example: if you choose equals to default values - then you will have wrong case with changed values will stay, when you returns default values by hand - they not saves.

2021-05-22 10:06 UTC, jdrueckert approved these changes
Tests out very nicely :+1:

2021-05-22 10:18 UTC, merged