feature: rework location change event
MovingBlocks/Terasology pull request #4705
Opened 2021-05-22 19:54 UTC by pollend

I changed the location change event to be handled on the next frame. if you change the location position then I mark the last position and prevent the last position/rotation from getting changed. only on the next update do I unlatch the flag so the location is relative to the last frame instead of whenever the component is changed then saved. this is more consistent since you could do something like this.
```
Entityref ref;

LocationComponent. ee = ref.getComponent(LocationComponent.class);

ref.saveComponent(ee); //
ref.saveComponent(ee);
```

2021-05-28 20:09 UTC, skaldarnar requested changes

2021-05-28 20:09 UTC, skaldarnar commented on engine/src/main/java/org/terasology/engine/logic/location/LocationChangedEvent.java
> +    public Vector3fc lastPosition() {
I think `last` and `current` works well here as naming. In `BeforeAfterEvent` we use `old` and `new` - was just wondering whether we should be consistent here :thinking:

2021-05-28 20:09 UTC, skaldarnar commented on engine/src/main/java/org/terasology/engine/logic/location/LocationChangedEvent.java
> +        return currentPosition.distance(lastPosition);
Same here.

2021-05-28 20:09 UTC, skaldarnar commented on engine/src/main/java/org/terasology/engine/logic/location/LocationChangedSystem.java
> +        for (EntityRef entity : process) {
Would be interesting to collect some metrics here on how many entities we typically process per tick. Could easily be added in a follow up PR, I guess.

2021-05-30 04:24 UTC, pollend commented on engine/src/main/java/org/terasology/engine/logic/location/LocationChangedEvent.java
> +        return currentPosition.sub(lastPosition, dest);
we don't actually use it in any capacity

2021-05-30 09:19 UTC, skaldarnar commented on engine/src/main/java/org/terasology/engine/logic/location/LocationChangedEvent.java
> +        return currentPosition.sub(lastPosition, dest);
We can keep it, that's not the problem. 

In particular, I think that 

```java
locationChange.vectorMoved(dest);
// or 
locationChange.positionDelta(dest);
```

is way better to read than doing the computation on receiver side

```java
locationChange.currentPosition().sub(locationChange.lastPosition(), dest);
```

2021-05-30 10:20 UTC, skaldarnar approved these changes

2021-05-30 10:52 UTC, merged