chore: rename engine-module.txt to module.txt
MovingBlocks/Terasology pull request #4722
Opened 2021-05-28 18:31 UTC by jdrueckert

Fixes #4646 

Tbh I have no idea, if this is what's expected to be done to resolve #4646 ...
I just thought I'd go for what I understood and use that as a basis for discussion :woman_shrugging: :sweat_smile:

2021-05-29 20:32 UTC, keturn commented on engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
> +        mmlm.put("module.txt", metadataReader);  // FIXME: this should be *only* for engine-module.
I think `module.txt` is `MODULE_INFO_FILENAME`, so we can remove this second `mmlm.put`.

2021-05-29 20:35 UTC, keturn requested changes
It looks like the one thing you left out of this PR titled "rename engine-module.txt to module.txt" was renaming `engine-module.txt`. 😜

2021-05-29 22:29 UTC, jdrueckert commented
> It looks like the one thing you left out of this PR titled "rename engine-module.txt to module.txt" was renaming `engine-module.txt`. stuck_out_tongue_winking_eye

Whoops :sweat_smile:

2021-05-29 23:15 UTC, keturn approved these changes

2021-05-29 23:20 UTC, keturn commented
Ah, _now_ it runs with passing tests!

I see versionInfo.properties is built with version information, and I believe the test cases will make sure that ModuleManager has a module of the appropriate name.

I think that the only thing left to confirm is that you can actually run a game world in a real process with other (non-engine) modules present. Can't think of anything else in particular to look for beyond that.

2021-05-30 04:23 UTC, pollend commented
@jdrueckert do you want to merge this?

2021-05-30 09:31 UTC, jdrueckert commented
> @jdrueckert do you want to merge this?

need to test it properly (as keturn mentioned) first, but once that's done: yes. 
any objections? @pollend

2021-05-30 10:24 UTC, jdrueckert commented
tests out fine in CoreGameplay, so I'll go ahead and merge this

2021-05-30 10:24 UTC, merged