fix: make BlockArea.iterator() use the same order as noise and facet data
MovingBlocks/Terasology pull request #4797
Opened 2021-06-25 22:40 UTC by tolziplohu

### Contains

Many facet providers use raw arrays of facet data and precalculated noise, which is more efficient. To get the position as well as the index, it would make sense to use `BlockArea.iterator()` and call `next()` on each loop. The problem is, facet and noise data increase the x coordinate first (`(0, 0), (1,  0), (2, 0)...`), but `BlockArea.iterator()` increases the y coordinate first (`(0, 1), (0, 1), (0, 2)...`). There's no good reason for that that I could find, so this PR switches it to the more intuitive x-first order that everything else uses, making it possible to both get the block positions and use subsampled noise efficiently in a facet provider.

### Outstanding before merging

Was there any reason for the y-first order here?

2021-06-26 05:20 UTC, pollend requested changes

2021-06-26 05:20 UTC, pollend commented on engine/src/main/java/org/terasology/engine/world/block/BlockArea.java
> +                        current.set(next);
can you add a test for this case. I think this doesn't cover the case if you call next() twice in a row without findNext(). I think I made the same mistake in BlockRegion.

2021-06-27 19:19 UTC, skaldarnar commented
As discussed in the mentor meeting on 2021-06-26 @tolziplohu will polish this PR a bit by 
- adding the requested test
- adding documentation to explicitly state the iterator contract (order of elements)

2021-06-29 17:08 UTC, tolziplohu commented
I added the test and the documentation.

@pollend:
> I think this doesn't cover the case if you call next() twice in a row without findNext(). I think I made the same mistake in BlockRegion.

Yeah, I added that line because I noticed that it wasn't working without calling `hasNext()` in between. It does look like BlockRegion has the same problem - should I fix that and add a test for it in this PR, or should that be separate?

2021-06-29 17:14 UTC, pollend approved these changes

2021-06-30 13:40 UTC, merged