feat(i18n): Update engine settings i18n
MovingBlocks/Terasology pull request #4935
Opened 2021-10-30 20:33 UTC by rzats

### Contains

A few strings in the core engine are currently untranslated - these are mostly found in the new autoconfig, as well as other settings. This fixes them to be properly i18n-able!

### How to test

Browse around the settings menu to see if everything looks OK.

### Outstanding before merging

None!

2021-10-31 16:39 UTC, Cervator commented
@rzats ! Now that's a name it is nice to see again. Welcome back 👋

2021-11-02 12:10 UTC, rzats commented
Thanks @Cervator! (I still do a little lurking on Discord every now and then 👀)

2021-11-23 07:25 UTC, DarkWeird requested changes
This PR break English Language.
```
10:23:18.705 [main] ERROR o.t.gestalt.assets.AssetType - Failed to load asset 'engine:menu_en'
java.io.IOException: Could not parse file 'menu_en.lang'
	at org.terasology.engine.i18n.assets.TranslationFormat.load(TranslationFormat.java:100)
	at org.terasology.engine.i18n.assets.TranslationFormat.load(TranslationFormat.java:38)
	....
Caused by: com.google.gson.JsonSyntaxException: duplicate key: settings-language
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
	...
```
funny fact:  breaking entry - `Language` 

Ukrainian works in described place.

2021-11-23 07:25 UTC, DarkWeird commented on engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
> +    "settings-language": "Language",
Duplicate entry. 
see Line 356

2021-11-29 11:45 UTC, DarkWeird commented on engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
> +    "settings-language": "Language",
@rzats

2021-11-29 12:46 UTC, rzats commented on engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
> +    "settings-language": "Language",
Fixed this and the merge conflict!

2021-11-29 12:51 UTC, DarkWeird approved these changes

2021-11-29 14:15 UTC, merged