gradle 8.3, bin, supporting java-20 via its kotlin dependency
MovingBlocks/Terasology pull request #5138
Opened 2023-09-18 04:00 UTC by soloturn

permits to remove hardcoded kotlin version, like mentioned in #5130.

2023-09-23 19:32 UTC, soloturn commented
tested with java-21, still good.

2023-09-23 20:05 UTC, soloturn commented
@BenjaminAmos am i allowed to ping you here as well?

2023-09-24 15:44 UTC, BenjaminAmos requested changes
We tend to use the `gradle-all` distribution over the `gradle-bin` distribution because it provides better IDE support.

2023-09-24 15:44 UTC, BenjaminAmos commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip
Although it is larger, we tend to use the `-all` gradle distribution because it makes the IDE tooling more useful.

2023-09-24 15:44 UTC, BenjaminAmos commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip
```suggestion
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
```

2023-09-30 00:23 UTC, soloturn commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip
done

2023-10-01 14:29 UTC, BenjaminAmos approved these changes
These changes seem fine to me.

I am approving this but will probably wait for a second opinion before merging.

2023-10-01 16:25 UTC, merged

2023-10-01 16:26 UTC, BenjaminAmos commented
To clarify the title here, this will probably only support Java 20. Running on Java 21 will likely need Gradle 8.4 (which is not yet released). It's still an improvement.

2023-10-01 16:39 UTC, jdrueckert commented
should we adjust the title in that case @BenjaminAmos ?

2023-10-02 15:45 UTC, soloturn commented
am running java-21.