TestCommit BrestNantes ListSkillScrollable
MovingBlocks/Terasology pull request #5183
Opened 2023-11-22 09:28 UTC by Yahiewi

### Contains

Brief description of what the PR does like "Fixes #12345"

### How to test

Brief description of how to test / confirm this PR before merging

### Outstanding before merging

If anything. You can use neat checkboxes! Feel free to delete if not needed

- [ ] Need to consider use case x
- [ ] Still have to adjust the wiki doc
- [ ] Will need translation work

2023-11-24 19:17 UTC, jdrueckert requested changes

2023-11-24 19:17 UTC, jdrueckert commented on .gitignore
> -!/modules/subprojects.gradle
We have a multi-repo workspace setup, so this change is not needed - on the contrary.
Please have a look at https://terasology.org/Terasology/#/Developing-Modules?id=understanding-terasology39s-git-setup and https://terasology.org/Terasology/#/Multi-Repo-Workspace to understand our workspace setup.

2023-11-25 09:08 UTC, soloturn requested changes
this change has 4 commits with the same commit message which makes it not easy to understand why a commit is there. it changes 62 files. personally i find it easy to read commit messages that follow this guideline: https://gist.github.com/finalfantasia/bd0070673ca27e5f7473

2024-04-21 18:42 UTC, closed without merging

2024-04-21 18:42 UTC, jdrueckert commented
Closing this PR as it was not intended. The author was working on a module-specific task and seems to have had issues with our multi-repo setup.