Terasology engine
MovingBlocks/Terasology pull request #5192
Opened 2023-12-06 04:55 UTC by soloturn

inttelij, checkstyle, pmd warnings removed.

2023-12-07 22:20 UTC, soloturn commented
is there a way to retrigger the jenkins build, apart from force pushing?

2023-12-07 23:51 UTC, BenjaminAmos commented
Under the checks tab on GitHub you should be able to re-run the tests if they fail. That appears to trigger a Jenkins re-run, as of recently (give https://github.com/MovingBlocks/Terasology/pull/5188/checks?check_run_id=19397149388 a try, for example). Some of the core contributors can force retrigger a build from the Jenkins UI but this relies on being added to a manual whitelist in the Logistics repository right now. If you're on that list then you can sign-in to Jenkins with your GitHub account to do that.

2023-12-08 08:11 UTC, soloturn commented
ok now checks are green. @BenjaminAmos @jdrueckert you mind merging?

2023-12-12 10:59 UTC, jdrueckert commented
> Under the checks tab on GitHub you should be able to re-run the tests if they fail. That appears to trigger a Jenkins re-run, as of recently (give https://github.com/MovingBlocks/Terasology/pull/5188/checks?check_run_id=19397149388 a try, for example). Some of the core contributors can force retrigger a build from the Jenkins UI but this relies on being added to a manual whitelist in the Logistics repository right now. If you're on that list then you can sign-in to Jenkins with your GitHub account to do that.

Alternatively, instead of force pushing, you can create an empty commit using the `allow-empty` parameter for `git commit`.

2023-12-16 18:02 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/world/time/WorldTimeImpl.java
>              return entity;
This seems like a valid warning. It is a strange construct to immediately return from a loop.

2023-12-16 21:53 UTC, soloturn commented on engine/src/main/java/org/terasology/engine/world/time/WorldTimeImpl.java
>              return entity;
suppress removed

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/audio/formats/OggReader.java
> -
Why did you remove these constants? They still appear to be relevant. It may be unused now but it could have been useful in the future.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/audio/formats/OggReader.java
> +                    CONVBUFFER[ptr + 1] = (byte) (bigEndian ? val : val >>> 8);
In this case, the `ptr + 0` may have been for clarity. It helps to keep the lines in alignment.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/logic/chat/ChatSystem.java
>      }
If you're going to change the purpose of the method, you might as well re-name it too. `joinWithWhitespace` seems more appropriate now than just a generic `join`.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
> +                hibernationSettings.ifPresent(hibernationManager -> hibernationManager.setHibernationAllowed(false));
Using functional methods, whilst more concise, have in the past caused performance issues. Streams and `List#forEach` were particularly poor in comparison to a for-each loop, Since this is in network code, I am slightly concerned about the potential impact here.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
> +            switch (java.util.Objects.requireNonNull(netComponent.replicateMode)) {
Is there a reason why this is fully-qualified? Usually you'd add an import for this, unless the name conflicts with another imported class.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/utilities/OperatingSystemMemory.java
> +        DATA(5);
I know that this says unused but as an enum the order of members matters. Removing enum members will re-order the existing ones, which might cause them to have the wrong ordinal values. It's quite normal for structs mapping low-level OS fields to contain "unused" or obsolete values. It's to maintain ABI compatibility.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/world/chunks/blockdata/ExtraBlockDataManager.java
> -                }
Did you mean to remove this part? It doesn't seem redundant.

2023-12-16 21:55 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/world/time/WorldTimeImpl.java
>              return entity;
If I had to try and re-write this code to work around the warning, it would probably be something like this:
```java
Iterable entitiesIterable = entityManager.getEntitiesWith(WorldComponent.class);
Iterator entityIterator = entitiesIterable.iterator()
return entityIterator.hasNext() ? entityIterator.next() : EntityRef.NULL;
```

2023-12-20 00:04 UTC, soloturn commented on engine/src/main/java/org/terasology/engine/world/chunks/blockdata/ExtraBlockDataManager.java
> -                }
this looks like dead code, v0 is set for nothing?

2023-12-20 17:42 UTC, soloturn commented
apart from one, reverted as mentioned in your review @BenjaminAmos .

2023-12-20 20:37 UTC, BenjaminAmos requested changes

2023-12-20 20:37 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/audio/formats/OggReader.java
> +                    CONVBUFFER[ptr + 8] = (byte) (bigEndian ? val >>> 8 : val);
```suggestion
                    CONVBUFFER[ptr + 0] = (byte) (bigEndian ? val >>> 8 : val);
```

2023-12-22 08:45 UTC, soloturn commented
@BenjaminAmos i did your requested change, but still it shows "change requested". it means you need to close this?

2023-12-23 21:36 UTC, BenjaminAmos approved these changes

2023-12-23 21:36 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/logic/console/ConsoleSystem.java
> +                        || !nuiManager.isOpen("engine:chat"))) {
This is a difficult condition to parse. I think you have rearranged it correctly but if a bug appears in this area then we might have to re-visit it.

2023-12-24 22:57 UTC, merged