refactor: replaced all whitelist and blacklist occurences by allowlis…
MovingBlocks/Terasology pull request #5277
Opened 2024-09-23 06:25 UTC by byhlel

…t and blocklist

We want to demonstrate our openness and inclusiveness in our code

Resolves #5275

### Contains

Resolves #5275 

### How to test

Everything works as before

### Outstanding before merging

2024-09-23 18:17 UTC, Cervator commented
This is eerily reminding me of #5276 - my apologies @byhlel for thinking you may _also_ be a bot or some sort of AI-assisted PR generator, but I'd like to ask for some sort of sign of humanity before considering this PR. 

Like just saying hello and what brought you here, and confirming that you've actually been able to run the game from source with the updates in place?

2024-09-23 18:20 UTC, byhlel commented
Hey,
I've just had some free time so I've been running around on good first issue.
I launched the game on a VN but im not on the best setup currently so I'd actually some review on this.
I'll try to rerun the game on another VM soon if no-one has time by then.

Also checking my profile would have reassured you on the latter.
Have a good one!

2024-09-23 18:27 UTC, Cervator commented
Oh phiew then - thanks for the quick reply, just a weird timing issue with the other PR and the barebones PR description. Maybe a tool that partially auto-created the PR out of a commit message or something?

I'd also be curious how you ran it on a VM, when trying in the past here that has gone ... poorly :-)

Any VM-induced performance issues aside so long as it builds and runs that's probably enough to call it validated 👍 

Although, considering that a rename of config files is included for a headless server run, that might be worth a quick check as well. And I wonder if we had any part of that automated for the test server setup / stored game server images we use 🤔 

This shouldn't be too bad to try out though, so maybe myself or another maintainer can check that soon. I'm on parental leave and have pretty minimal time, just spotted this by chance. I'll try to keep this in a tab near the top of my browser and see if I can get to it :-)

Much appreciated!

2024-09-24 05:35 UTC, byhlel commented
No I just like to keep my commits as concise as possible and respecting the repo's guideline.
So unfortunately (or fortunately) no tools neither to commit nor PR except from maybe lazyness to describe further the PR which was to me straightforward.

![image](https://github.com/user-attachments/assets/cc1a2547-a1c8-4642-a6ad-0fedba83e4fc)

Seems fine to me but further review to make sure nothing was accidently broken might be relevant here.

2024-09-25 18:16 UTC, BenjaminAmos requested changes
Thanks for doing this. We have sadly had pull requests that were very suspect in the recent past but they were clearly so (like #5264) and nothing like this. We are quite happy to accept quality contributions from anyone.

Ordinarily though, renaming APIs would be a breaking change that would need a strong justification to warrant large-scale changes to our module ecosystem.

The changes here, however, appear minimal and only affect internal APIs, so I see no harm in accepting it, so long as backwards compatiblity is maintained. Currently with these changes `whitelist.json` and `blacklist.json` will no longer be read. If you could change this to accept both old and file names still then it should work well.

2024-09-25 18:16 UTC, BenjaminAmos commented on .gitignore
> +denylist.json
Can we please retain the old flle names in the gitignore so that they are not accidentally committed from older workspaces in future?

2024-09-25 18:16 UTC, BenjaminAmos commented on docs/Modding-API.md
> +Terasology's engine uses allowlisting approach to expose an API for modules using two primary methods and a rarely needed third one:
```suggestion
Terasology's engine uses an allowlisting approach to expose an API for modules using two primary methods and a rarely needed third one:
```

2024-09-25 18:16 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/network/internal/ServerConnectListManager.java
> +        allowlistPath = PathManager.getInstance().getHomePath().resolve("allowlist.json");
Since this is likely to a breaking change otherwise, can we continue to check for the old file names if the newer ones do not exist?

2024-09-25 18:16 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectGameScreen.java
> +            if (!Files.exists(denylistPath)) {
Could you please check for the presence of the old file names if the new ones do not exist?

2024-09-25 18:16 UTC, BenjaminAmos commented on docs/Modding-API.md
> +Terasology's engine uses allowlisting approach to expose an API for modules using two primary methods and a rarely needed third one:
Or alternatively:
```suggestion
Terasology's engine uses allowlisting to expose an API for modules using two primary methods and a rarely needed third one:
```

2024-09-26 04:54 UTC, byhlel commented
Yes thank you for pointing this out, hadn't thought much of backwards compatibility!

2024-09-26 04:54 UTC, byhlel commented on .gitignore
> +denylist.json
applied

2024-09-26 04:54 UTC, byhlel commented on docs/Modding-API.md
> +Terasology's engine uses allowlisting approach to expose an API for modules using two primary methods and a rarely needed third one:
applied

2024-09-26 04:54 UTC, byhlel commented on engine/src/main/java/org/terasology/engine/network/internal/ServerConnectListManager.java
> +        allowlistPath = PathManager.getInstance().getHomePath().resolve("allowlist.json");
applied

2024-09-26 04:54 UTC, byhlel commented on engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectGameScreen.java
> +            if (!Files.exists(denylistPath)) {
applied

2024-09-29 18:31 UTC, BenjaminAmos requested changes

2024-09-29 18:31 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectGameScreen.java
>          }
As I understand this logic, it is not quite correct. I was not paying full attention last time to this area. Now it creates `blacklist.json` and `whitelist.json` files if no files are present, I think. It should never create new `blacklist.json` and `whitelist.json` files, so if those are present then the check for the corresponding new names can just be skipped.

All that this code should be doing is creating empty files if they do not exist, rather than trying to load them in. As such, it should not be creating files with the old names and should skip creating files with the new names if those old-named files are already present.

2024-09-29 18:31 UTC, BenjaminAmos commented on engine/src/main/java/org/terasology/engine/network/internal/ServerConnectListManager.java
> +        }
```suggestion
        // Check for old naming first to retain compatiblity, otherwise use new naming by default.
        Path potentialDenylistPath = PathManager.getInstance().getHomePath().resolve("blacklist.json");
        Path potentialAllowlistPath = PathManager.getInstance().getHomePath().resolve("whitelist.json");
        if (!Files.exists(potentialDenylistPath)) {
            potentialDenylistPath = PathManager.getInstance().getHomePath().resolve("denylist.json");
        }
        if (!Files.exists(potentialAllowlistPath)) {
            potentialAllowlistPath = PathManager.getInstance().getHomePath().resolve("allowlist.json");
        }
        denylistPath = potentialDenylistPath;
        allowlistPath = potentialAllowlistPath;
```

`denylistPath` and `allowlistPath` are final variables, so they can only be assigned once in the constructor. Using a temporary variable here should work (but I wrote this quickly so please test that it compiles and works).

2026-04-10 20:23 UTC, Cervator commented
Closing this as superseded by #5324 which just merged

2026-04-10 20:23 UTC, closed without merging