Code Optimization in TeraArrayBenchmark.java
MovingBlocks/Terasology pull request #5295
Opened 2024-12-26 16:51 UTC by BabbaWaagen

### Contains
Code Optimization in TeraArrayBenchmark.java

ByteBuffer.allocateDirect-> Better performance through direct ByteBuffer.

Pre-loading of sizes-> Minimizes method calls in inner loops.

Use of flip-> Optimizes ByteBuffer for read operations.

Clarity and consistency-> Uniform names and code style improve readability.

2024-12-26 23:04 UTC, Cervator commented
Hi @BabbaWaagen and welcome!

I hope you don't mind terribly if I ask you a bit more about yourself and your interest in Terasology first, as well as whether you have any actual benchmark metrics to prove the performance benefits?

We have had PRs submitted before that essentially seem like somebody (probably even with good intentions) fed a Terasology class into a GenAI agent to ask for improvements - without necessarily understanding the impact or even the game itself.

In this case for instance there is a code style violation introduced, some puzzling private to package scope changes, and typo fixes that might actually break binary compatibility for previous worlds - which isn't necessarily a big deal, but does make me wonder

Let me know please and I hope you won't feel offended about me being a little paranoid! Thank you

2024-12-29 10:28 UTC, BenjaminAmos requested changes
It is unclear whether this actually improves anything. It only seems to shuffle things around in the benchmark measuring performance, rather than improving any of our actual code.

`ByteBuffer#allocate` -> `ByteBuffer#allocateDirect` may be more performant at the expense of a higher creation cost. Everything else seems so trivial that I would hope it would be optimised away by the JIT anyway.

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> +import org.openjdk.jmh.annotations.*;
We have guidelines that discourage wildcard imports: https://terasology.org/Terasology/#/Code-Conventions?id=starred-imports. It also shows up as a warning when running Checkstyle. Can you please revert this back?

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> -        for (int y = 0; y < state.array.getSizeY(); y++) {
Do you have any evidence that this provides any practical performance benefit? I would assume that the compiler (or even JIT) would be able to inline simple getter calls like this.

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> +        ByteBuffer out;
What advantage does making this package-private bring? I would have thought that private members could be better optimised due to a lack of unknown observers.

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> +        ByteBuffer in;
Is there a reason why you have made this package-private?

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> +        TeraArray array;
Is there a reason why you have made these package-private?

2024-12-29 10:28 UTC, BenjaminAmos commented on engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
> +            in.flip();
The semantics of your replacement are not quite the same: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/ByteBuffer.html#flip(). If you are sure that `ByteBuffer#flip` is both functionally equivalent here and performs better then this may be acceptable. It is not clear from a glance though that we will always read exactly to the end of a buffer.

2024-12-29 22:05 UTC, Cervator commented
Honestly at this point with no response I'm leaning toward this going into the "arbitrary pointless submission" category 😕

2024-12-30 00:13 UTC, closed without merging